# Generated by Django 5.1.1 on 2024-12-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FashionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('MenTopWear', 'MenTopWear'), ('MenBottomWear', 'MenBottomWear'), ('MenFootWear', 'MenFootWear'), ('WomenEthnicWear', 'WomenEthnicWear'), ('WomenFootWear', 'WomenFootWear'), ('kids', 'kids')], max_length=50)),
                ('brand', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('rating_rate', models.FloatField(verbose_name='Average Rating')),
                ('rating_count', models.IntegerField(verbose_name='Total Ratings')),
                ('rating_review', models.IntegerField(verbose_name='Total Review')),
                ('size', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
