# Generated by Django 5.1.1 on 2024-12-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fashion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fashionmodel',
            name='seller',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
