# Generated by Django 5.1.1 on 2024-12-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CameraLaptopModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Camera', 'Camera'), ('Laptop', 'Laptop')], max_length=50)),
                ('brand', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('rating_rate', models.FloatField(verbose_name='Average Rating')),
                ('rating_count', models.IntegerField(verbose_name='Total Ratings')),
                ('rating_review', models.IntegerField(verbose_name='Total Review')),
                ('highlight_1', models.CharField(blank=True, max_length=500, null=True)),
                ('highlight_2', models.CharField(blank=True, max_length=500, null=True)),
                ('highlight_3', models.CharField(blank=True, max_length=500, null=True)),
                ('highlight_4', models.CharField(blank=True, max_length=500, null=True)),
                ('highlight_5', models.CharField(blank=True, max_length=500, null=True)),
                ('seller', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeadMobilePowerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Headphone', 'Headphone'), ('MobileAcc', 'MobileAcc'), ('Powerbank', 'Powerbank')], max_length=50)),
                ('brand', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('rating_rate', models.FloatField(verbose_name='Average Rating')),
                ('rating_count', models.IntegerField(verbose_name='Total Ratings')),
                ('rating_review', models.IntegerField(verbose_name='Total Review')),
                ('seller', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
