# Generated by Django 5.1.1 on 2024-12-26 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics', '0002_alter_cameralaptopmodel_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CameraLaptopModel',
            new_name='ElectronicsModel',
        ),
        migrations.DeleteModel(
            name='HeadMobilePowerModel',
        ),
    ]
