# Generated by Django 5.1.1 on 2024-12-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics', '0003_rename_cameralaptopmodel_electronicsmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronicsmodel',
            name='category',
            field=models.CharField(choices=[('Camera', 'Camera'), ('Laptop', 'Laptop'), ('Headphone', 'Headphone'), ('MobileAcc', 'MobileAcc'), ('Powerbank', 'Powerbank'), ('TV', 'TV'), ('WashingMachine', 'WashingMachine'), ('AC', 'AC'), ('Refrigerators', 'Refrigerators')], max_length=50),
        ),
    ]
