# Generated by Django 5.1.1 on 2024-12-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics', '0004_alter_electronicsmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronicsmodel',
            name='category',
            field=models.CharField(choices=[('Camera', 'Camera'), ('Laptop', 'Laptop'), ('Headphone', 'Headphone'), ('MobileAcc', 'MobileAcc'), ('Powerbank', 'Powerbank'), ('TV', 'TV'), ('WashingMachine', 'WashingMachine'), ('AC', 'AC'), ('Refrigerators', 'Refrigerators'), ('Mobile', 'Mobile')], max_length=50),
        ),
    ]
