# Generated by Django 5.1.1 on 2024-12-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=100, verbose_name='Name')),
                ('number', models.CharField(max_length=10, verbose_name='Mobile Number')),
                ('pincode', models.CharField(max_length=6, verbose_name='Pincode')),
                ('locality', models.CharField(blank=True, max_length=150, verbose_name='Locality')),
                ('address', models.TextField(verbose_name='Address (Area / Street)')),
                ('city', models.CharField(max_length=100, verbose_name='City/District/Town')),
                ('state', models.CharField(choices=[('Uttarakhand', 'Uttarakhand'), ('Bihar', 'Bihar'), ('Haryana', 'Haryana'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Delhi', 'Delhi'), ('Tamil Nadu', 'Tamil Nadu')], max_length=50, verbose_name='State')),
                ('landmark', models.CharField(blank=True, max_length=150, null=True, verbose_name='Landmark (Optional)')),
                ('alternate_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Alternate Phon(Optional)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
