# Generated by Django 5.1.1 on 2024-12-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Log_In', '0004_myordersmodel_order_id_myordersmodel_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myordersmodel',
            name='order_id',
        ),
        migrations.AlterField(
            model_name='myordersmodel',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
