# Generated by Django 5.1.1 on 2024-12-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Log_In', '0007_myordersmodel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(max_length=500, verbose_name='Address (Area / Street)'),
        ),
        migrations.AlterField(
            model_name='address',
            name='number',
            field=models.CharField(max_length=10, unique=True, verbose_name='Mobile Number'),
        ),
    ]
