# Generated by Django 5.1.1 on 2025-01-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Log_In', '0008_alter_address_address_alter_address_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_img', models.ImageField(default='profile.png', upload_to='')),
            ],
        ),
    ]
