# Generated by Django 5.1.1 on 2025-01-02 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Log_In', '0010_profileimage_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileimage',
            old_name='profile_img',
            new_name='image',
        ),
    ]
