# Generated by Django 5.1.1 on 2024-12-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('Apple', 'Apple'), ('Samsung', 'Samsung'), ('Realme', 'Realme'), ('Poco', 'Poco'), ('OnePlus', 'OnePlus')], max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('storage', models.CharField(max_length=50)),
                ('ram', models.CharField(max_length=50)),
                ('display', models.CharField(max_length=100)),
                ('front_camera', models.CharField(max_length=50, verbose_name='Front Camera')),
                ('rear_camera', models.CharField(max_length=50, verbose_name='Rear Camera')),
                ('battery_capacity', models.IntegerField(verbose_name='Battery Capacity (mAh)')),
                ('rating_rate', models.FloatField(verbose_name='Average Rating')),
                ('rating_count', models.IntegerField(verbose_name='Total Ratings')),
                ('rating_review', models.TextField(blank=True, null=True, verbose_name='Top Review')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
