# Generated by Django 5.1.1 on 2024-12-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mobiles_Tab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='rating_review',
            field=models.IntegerField(default=25, verbose_name='Total Review'),
            preserve_default=False,
        ),
    ]
