# Generated by Django 5.1.1 on 2024-12-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mobiles_Tab', '0003_mobile_processor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='display',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='front_camera',
            field=models.CharField(blank=True, max_length=50, verbose_name='Front Camera'),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='ram',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
