# Generated by Django 5.1.1 on 2024-12-27 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mobiles_Tab', '0004_alter_mobile_display_alter_mobile_front_camera_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mobile',
        ),
    ]
